"""unit/infra (CLAUDE.md §9.1, tasks/01-realism step 3): automatic block data generated by tools/gen_infra.py."""

from __future__ import annotations

from collections import defaultdict

from app.railcore.infra import get_world

WORLD = get_world()
INFRA = WORLD.infra


def test_block_sections_tile_every_segment():
    by_seg = defaultdict(list)
    for b in INFRA.blocks:
        by_seg[b.segment_id].append(b)
    assert set(by_seg) == set(WORLD.segments)
    for seg_id, blocks in by_seg.items():
        seg = WORLD.segments[seg_id]
        blocks.sort(key=lambda b: b.index)
        assert 6 <= len(blocks) <= 7, f"{seg_id}: {len(blocks)} block sections"
        assert [b.index for b in blocks] == list(range(1, len(blocks) + 1))
        assert blocks[0].from_m == 0 and blocks[-1].to_m == seg.length_m
        for a, b in zip(blocks, blocks[1:]):
            assert a.to_m == b.from_m, f"{seg_id}: gap or overlap between {a.id} and {b.id}"
        assert sum(b.to_m - b.from_m for b in blocks) == seg.length_m
        assert all(b.id == f"{seg_id}-B{b.index}" for b in blocks)


def test_block_signals_both_directions_and_pre_entry():
    for seg_id, seg in WORLD.segments.items():
        sigs = [s for s in INFRA.signals if s.segment_id == seg_id]
        bounds = sorted({b.to_m for b in INFRA.blocks if b.segment_id == seg_id and b.to_m < seg.length_m})
        for d, suffix in (("odd", "N"), ("even", "C")):
            ds = sorted((s for s in sigs if s.direction.value == d), key=lambda s: s.pos_m)
            assert [s.pos_m for s in ds] == bounds, f"{seg_id} {d}: a block signal on every inner boundary"
            assert all(s.id.endswith(suffix) for s in ds)
            pre = [s for s in ds if s.kind == "pre_entry"]
            assert len(pre) == 1, f"{seg_id} {d}: exactly one pre-entry signal"
            # the last block signal before the station in the direction of travel
            assert pre[0].pos_m == (bounds[-1] if d == "odd" else bounds[0])


def test_station_signals_and_simultaneous_reception():
    for st in INFRA.stations:
        ids = {s.id for s in INFRA.signals if s.station_id == st.id}
        assert ids == {f"{st.id}-{d}-{k}" for d in ("odd", "even") for k in ("entry", "exit")}
        assert st.simultaneous_reception == (st.kind == "station"), f"{st.id}: sidings receive one at a time"
